 	gdk_pixbuf_loader_new 	 PROTO :VARARG
  	gdk_pixbuf_loader_new_with_type 	 PROTO :VARARG
  	gdk_pixbuf_loader_new_with_mime_type 	 PROTO :VARARG
  	gdk_pixbuf_loader_get_format 	 PROTO :VARARG
 	gdk_pixbuf_loader_write 	 PROTO :VARARG
 	gdk_pixbuf_loader_write_bytes 	 PROTO :VARARG
 	gdk_pixbuf_loader_set_size 	 PROTO :VARARG
  	gdk_pixbuf_loader_get_pixbuf 	 PROTO :VARARG
  	gdk_pixbuf_loader_get_animation 	 PROTO :VARARG
 	gdk_pixbuf_loader_close  		PROTO :VARARG
 	
  	gdk_pixbuf_get_from_window PROTO :VARARG 
  	gdk_pixbuf_get_from_surface PROTO :VARARG 
  	
