	gdk_window_create_similar_surface PROTO :VARARG 
	gdk_window_create_similar_image_surface PROTO :VARARG 
	gdk_cairo_create PROTO :VARARG 
	gdk_cairo_get_clip_rectangle PROTO :VARARG 
	gdk_cairo_get_drawing_context PROTO :VARARG 
	gdk_cairo_set_source_color PROTO :VARARG 
	gdk_cairo_set_source_rgba PROTO :VARARG 
	gdk_cairo_set_source_pixbuf PROTO :VARARG 
	gdk_cairo_set_source_window PROTO :VARARG 
	gdk_cairo_rectangle PROTO :gpointer,:REAL8,:REAL8,:REAL8,:REAL8 
	gdk_cairo_region PROTO :VARARG 
	gdk_cairo_region_create_from_surface PROTO :VARARG 
	gdk_cairo_surface_create_from_pixbuf PROTO :VARARG 
	gdk_cairo_draw_from_gl PROTO :VARARG 
	
