	gtk_source_language_get_id 	 PROTO :VARARG
 	gtk_source_language_get_name 	 PROTO :VARARG
 	gtk_source_language_get_section 	 PROTO :VARARG
 	gtk_source_language_get_hidden 	 PROTO :VARARG
 	gtk_source_language_get_metadata 	 PROTO :VARARG
 	gtk_source_language_get_mime_types 	 PROTO :VARARG
 	gtk_source_language_get_globs 	 PROTO :VARARG
 	gtk_source_language_get_style_name 	 PROTO :VARARG
 	gtk_source_language_get_style_ids 	 PROTO :VARARG
 	gtk_source_language_get_style_fallback 	 PROTO :VARARG
 
