  
		gtk_menu_item_new  PROTO :VARARG 
		gtk_menu_item_new_with_label  PROTO :VARARG 
		gtk_menu_item_new_with_mnemonic  PROTO :VARARG 
		gtk_menu_item_set_right_justified  PROTO :VARARG 
		gtk_menu_item_get_right_justified  PROTO :VARARG 
		gtk_menu_item_get_label  PROTO :VARARG 
		gtk_menu_item_set_label  PROTO :VARARG 
		gtk_menu_item_get_use_underline  PROTO :VARARG 
		gtk_menu_item_set_use_underline  PROTO :VARARG 
		gtk_menu_item_set_submenu  PROTO :VARARG 
		gtk_menu_item_get_submenu  PROTO :VARARG 
		gtk_menu_item_set_accel_path  PROTO :VARARG 
		gtk_menu_item_get_accel_path  PROTO :VARARG 
		gtk_menu_item_select  PROTO :VARARG 
		gtk_menu_item_deselect  PROTO :VARARG 
		gtk_menu_item_activate  PROTO :VARARG 
		gtk_menu_item_toggle_size_request  PROTO :VARARG 
		gtk_menu_item_toggle_size_allocate  PROTO :VARARG 
		gtk_menu_item_get_reserve_indicator  PROTO :VARARG 
		gtk_menu_item_set_reserve_indicator  PROTO :VARARG 
	
