	gtk_source_language_manager_new 	 PROTO :VARARG
 	gtk_source_language_manager_get_default 	 PROTO :VARARG
 	gtk_source_language_manager_set_search_path 	 PROTO :VARARG
 	gtk_source_language_manager_get_search_path 	 PROTO :VARARG
 	gtk_source_language_manager_get_language_ids 	 PROTO :VARARG
 	gtk_source_language_manager_get_language 	 PROTO :VARARG
 	gtk_source_language_manager_guess_language 	 PROTO :VARARG
 
