 
  	gtk_source_style_scheme_manager_new 	 PROTO :VARARG
  	gtk_source_style_scheme_manager_get_default 	 PROTO :VARARG
 	gtk_source_style_scheme_manager_set_search_path 	 PROTO :VARARG
 	gtk_source_style_scheme_manager_append_search_path 	 PROTO :VARARG
 	gtk_source_style_scheme_manager_prepend_search_path 	 PROTO :VARARG
    	gtk_source_style_scheme_manager_get_search_path 	 PROTO :VARARG
     	gtk_source_style_scheme_manager_get_scheme_ids 	 PROTO :VARARG
  	gtk_source_style_scheme_manager_get_scheme 	 PROTO :VARARG
 	gtk_source_style_scheme_manager_force_rescan 	 PROTO :VARARG
 
