 	gtk_entry_buffer_new  PROTO :VARARG 
  	gtk_entry_buffer_get_text  PROTO :VARARG 
	gtk_entry_buffer_set_text  PROTO :VARARG 
	gtk_entry_buffer_get_bytes  PROTO :VARARG 
	gtk_entry_buffer_get_length  PROTO :VARARG 
	gtk_entry_buffer_get_max_length  PROTO :VARARG 
	gtk_entry_buffer_set_max_length  PROTO :VARARG 
	gtk_entry_buffer_insert_text  PROTO :VARARG 
	gtk_entry_buffer_delete_text  PROTO :VARARG 
	gtk_entry_buffer_emit_deleted_text  PROTO :VARARG 
	gtk_entry_buffer_emit_inserted_text  PROTO :VARARG 
	
