 	gtk_cell_view_new  PROTO :VARARG 
 	gtk_cell_view_new_with_text  PROTO :VARARG 
 	gtk_cell_view_new_with_markup  PROTO :VARARG 
 	gtk_cell_view_new_with_pixbuf  PROTO :VARARG 
	gtk_cell_view_set_model  PROTO :VARARG 
 	gtk_cell_view_get_model  PROTO :VARARG 
	gtk_cell_view_set_displayed_row  PROTO :VARARG 
 	gtk_cell_view_get_displayed_row  PROTO :VARARG 
	gtk_cell_view_get_size_of_row  PROTO :VARARG 
	gtk_cell_view_set_background_color  PROTO :VARARG 
 	gtk_cell_view_get_cell_renderers  PROTO :VARARG 

