		gtk_message_dialog_new  PROTO :VARARG 
		gtk_message_dialog_new_with_markup  PROTO :VARARG 
		gtk_message_dialog_set_markup  PROTO :VARARG 
		gtk_message_dialog_set_image  PROTO :VARARG 
		gtk_message_dialog_get_image  PROTO :VARARG 
		gtk_message_dialog_format_secondary_text  PROTO :VARARG 
		gtk_message_dialog_format_secondary_markup  PROTO :VARARG 
		gtk_message_dialog_get_message_area  PROTO :VARARG 
		

		enum GTK_BUTTONS_NONE,GTK_BUTTONS_OK,GTK_BUTTONS_CLOSE,GTK_BUTTONS_CANCEL,GTK_BUTTONS_YES_NO,GTK_BUTTONS_OK_CANCEL
