	gtk_dialog_new PROTO :VARARG 
	gtk_dialog_new_with_buttons PROTO :VARARG 
	gtk_dialog_run PROTO :VARARG 
	gtk_dialog_response PROTO :VARARG 
	gtk_dialog_add_button PROTO :VARARG 
	gtk_dialog_add_buttons PROTO :VARARG 
	gtk_dialog_add_action_widget PROTO :VARARG 
	gtk_dialog_set_default_response PROTO :VARARG 
	gtk_dialog_set_response_sensitive PROTO :VARARG 
	gtk_dialog_get_response_for_widget PROTO :VARARG 
	gtk_dialog_get_widget_for_response PROTO :VARARG 
	gtk_dialog_get_action_area PROTO :VARARG 
	gtk_dialog_get_content_area PROTO :VARARG 
	gtk_dialog_get_header_bar PROTO :VARARG 
	gtk_alternative_dialog_button_order PROTO :VARARG 
	gtk_dialog_set_alternative_button_order PROTO :VARARG 
	gtk_dialog_set_alternative_button_order_from_array PROTO :VARARG 
	
	GTK_DIALOG_MODAL               = 1 
	GTK_DIALOG_DESTROY_WITH_PARENT = 2
	GTK_DIALOG_USE_HEADER_BAR      = 4

