 	gtk_paned_new  PROTO :VARARG 
	gtk_paned_add1  PROTO :VARARG 
	gtk_paned_add2  PROTO :VARARG 
	gtk_paned_pack1  PROTO :VARARG 
	gtk_paned_pack2  PROTO :VARARG 
 	gtk_paned_get_child1  PROTO :VARARG 
 	gtk_paned_get_child2  PROTO :VARARG 
	gtk_paned_set_position  PROTO :VARARG 
	gtk_paned_get_position  PROTO :VARARG 
 	gtk_paned_get_handle_window  PROTO :VARARG 
	gtk_paned_set_wide_handle  PROTO :VARARG 
	gtk_paned_get_wide_handle  PROTO :VARARG 
	
