
		g_convert  PROTO :VARARG 
		g_convert_with_fallback  PROTO :VARARG 
		g_convert_with_iconv  PROTO :VARARG 
		g_iconv_open  PROTO :VARARG 
		g_iconv  PROTO :VARARG 
		g_iconv_close  PROTO :VARARG 
		g_locale_to_utf8  PROTO :VARARG 
		g_filename_to_utf8  PROTO :VARARG 
		g_filename_from_utf8  PROTO :VARARG 
		g_get_filename_charsets  PROTO :VARARG 
		g_filename_display_name  PROTO :VARARG 
		g_filename_display_basename  PROTO :VARARG 
		g_locale_from_utf8  PROTO :VARARG 
		g_get_charset  PROTO :VARARG 
		g_get_codeset  PROTO :VARARG 
		g_get_console_charset  PROTO :VARARG 
	
