
 	g_content_type_equals 	 PROTO :VARARG
 	g_content_type_is_a 	 PROTO :VARARG
 	g_content_type_is_mime_type 	 PROTO :VARARG
 	g_content_type_is_unknown 	 PROTO :VARARG
 	g_content_type_get_description 	 PROTO :VARARG
 	g_content_type_get_mime_type 	 PROTO :VARARG
 	g_content_type_get_icon 	 PROTO :VARARG
 	g_content_type_get_symbolic_icon 	 PROTO :VARARG
 	g_content_type_get_generic_icon_name 	 PROTO :VARARG
 	g_content_type_can_be_executable 	 PROTO :VARARG
 	g_content_type_from_mime_type 	 PROTO :VARARG
 	g_content_type_guess 	 PROTO :VARARG
 	g_content_type_guess_for_tree 	 PROTO :VARARG
 	g_content_types_get_registered 	 PROTO :VARARG
 
