  	gdk_pixbuf_new_from_file PROTO :VARARG 
  	gdk_pixbuf_new_from_file_at_size PROTO :VARARG 
  	gdk_pixbuf_new_from_file_at_scale PROTO :VARARG 
  	gdk_pixbuf_get_file_info PROTO :VARARG 
 	gdk_pixbuf_get_file_info_async PROTO :VARARG 
  	gdk_pixbuf_get_file_info_finish PROTO :VARARG 
  	gdk_pixbuf_new_from_resource PROTO :VARARG 
  	gdk_pixbuf_new_from_resource_at_scale PROTO :VARARG 
  	gdk_pixbuf_new_from_stream PROTO :VARARG 
 	gdk_pixbuf_new_from_stream_async PROTO :VARARG 
  	gdk_pixbuf_new_from_stream_finish PROTO :VARARG 
  	gdk_pixbuf_new_from_stream_at_scale PROTO :VARARG 
 	gdk_pixbuf_new_from_stream_at_scale_async PROTO :VARARG 
 	
