 
  	gtk_combo_box_text_new 	PROTO	:VARARG
  	gtk_combo_box_text_new_with_entry 	PROTO	:VARARG
 	gtk_combo_box_text_append 	PROTO	:VARARG
 	gtk_combo_box_text_prepend 	PROTO	:VARARG
 	gtk_combo_box_text_insert 	PROTO	:VARARG
 	gtk_combo_box_text_append_text 	PROTO	:VARARG
 	gtk_combo_box_text_prepend_text 	PROTO	:VARARG
 	gtk_combo_box_text_insert_text 	PROTO	:VARARG
 	gtk_combo_box_text_remove 	PROTO	:VARARG
 	gtk_combo_box_text_remove_all 	PROTO	:VARARG
  	gtk_combo_box_text_get_active_text 	PROTO	:VARARG
  	
