

	 	gtk_file_filter_new  PROTO :VARARG 
		gtk_file_filter_set_name  PROTO :VARARG 
	  	gtk_file_filter_get_name  PROTO :VARARG 
		gtk_file_filter_add_mime_type  PROTO :VARARG 
		gtk_file_filter_add_pattern  PROTO :VARARG 
		gtk_file_filter_add_pixbuf_formats  PROTO :VARARG 
		gtk_file_filter_add_custom  PROTO :VARARG 
		gtk_file_filter_get_needed  PROTO :VARARG 
		gtk_file_filter_filter  PROTO :VARARG 
	 	gtk_file_filter_new_from_gvariant  PROTO :VARARG 
	 	gtk_file_filter_to_gvariant  PROTO :VARARG 

	
