	gtk_box_new  PROTO :VARARG 
	gtk_box_pack_start  PROTO :VARARG 
	gtk_box_pack_end  PROTO :VARARG 
	gtk_box_get_homogeneous  PROTO :VARARG 
	gtk_box_set_homogeneous  PROTO :VARARG 
	gtk_box_get_spacing  PROTO :VARARG 
	gtk_box_set_spacing  PROTO :VARARG 
	gtk_box_reorder_child  PROTO :VARARG 
	gtk_box_query_child_packing  PROTO :VARARG 
	gtk_box_set_child_packing  PROTO :VARARG 
	gtk_box_get_baseline_position  PROTO :VARARG 
	gtk_box_set_baseline_position  PROTO :VARARG 
	gtk_box_get_center_widget  PROTO :VARARG 
	gtk_box_set_center_widget  PROTO :VARARG 
	
