  	gtk_source_mark_attributes_new PROTO :VARARG 
 	gtk_source_mark_attributes_set_background PROTO :VARARG 
 	gtk_source_mark_attributes_get_background PROTO :VARARG 
 	gtk_source_mark_attributes_set_icon_name PROTO :VARARG 
   	gtk_source_mark_attributes_get_icon_name PROTO :VARARG 
 	gtk_source_mark_attributes_set_gicon PROTO :VARARG 
  	gtk_source_mark_attributes_get_gicon PROTO :VARARG 
 	gtk_source_mark_attributes_set_pixbuf PROTO :VARARG 
 	gtk_source_mark_attributes_get_pixbuf PROTO :VARARG 
 	gtk_source_mark_attributes_render_icon PROTO :VARARG 
  	gtk_source_mark_attributes_get_tooltip_text PROTO :VARARG 
  	gtk_source_mark_attributes_get_tooltip_markup PROTO :VARARG 

