	gtk_image_get_icon_set 	 PROTO :VARARG
  	gtk_image_get_pixbuf 	 PROTO :VARARG
 	gtk_image_get_stock 	 PROTO :VARARG
  	gtk_image_get_animation 	 PROTO :VARARG
 	gtk_image_get_icon_name 	 PROTO :VARARG
 	gtk_image_get_gicon 	 PROTO :VARARG
 	gtk_image_get_storage_type 	 PROTO :VARARG
  	gtk_image_new_from_file 	 PROTO :VARARG
  	gtk_image_new_from_icon_set 	 PROTO :VARARG
  	gtk_image_new_from_pixbuf 	 PROTO :VARARG
  	gtk_image_new_from_stock 	 PROTO :VARARG
  	gtk_image_new_from_animation 	 PROTO :VARARG
  	gtk_image_new_from_icon_name 	 PROTO :VARARG
  	gtk_image_new_from_gicon 	 PROTO :VARARG
  	gtk_image_new_from_resource 	 PROTO :VARARG
  	gtk_image_new_from_surface 	 PROTO :VARARG
 	gtk_image_set_from_file 	 PROTO :VARARG
 	gtk_image_set_from_icon_set 	 PROTO :VARARG
 	gtk_image_set_from_pixbuf 	 PROTO :VARARG
 	gtk_image_set_from_stock 	 PROTO :VARARG
 	gtk_image_set_from_animation 	 PROTO :VARARG
 	gtk_image_set_from_icon_name 	 PROTO :VARARG
 	gtk_image_set_from_gicon 	 PROTO :VARARG
 	gtk_image_set_from_resource 	 PROTO :VARARG
 	gtk_image_set_from_surface 	 PROTO :VARARG
 	gtk_image_clear 	 PROTO :VARARG
  	gtk_image_new 	 PROTO :VARARG
 	gtk_image_set_pixel_size 	 PROTO :VARARG
 	gtk_image_get_pixel_size  PROTO :VARARG
 	
 	enum  GTK_ICON_SIZE_INVALID,\
		  GTK_ICON_SIZE_MENU,\
		  GTK_ICON_SIZE_SMALL_TOOLBAR,\
		  GTK_ICON_SIZE_LARGE_TOOLBAR,\
		  GTK_ICON_SIZE_BUTTON,\
		  GTK_ICON_SIZE_DND,\
		  GTK_ICON_SIZE_DIALOG

