 	gtk_source_search_settings_new 		PROTO :VARARG
 	gtk_source_search_settings_get_search_text 		PROTO :VARARG
 	gtk_source_search_settings_set_search_text 		PROTO :VARARG
 	gtk_source_search_settings_get_case_sensitive 		PROTO :VARARG
 	gtk_source_search_settings_set_case_sensitive 		PROTO :VARARG
 	gtk_source_search_settings_get_at_word_boundaries 		PROTO :VARARG
 	gtk_source_search_settings_set_at_word_boundaries 		PROTO :VARARG
 	gtk_source_search_settings_get_wrap_around 		PROTO :VARARG
 	gtk_source_search_settings_set_wrap_around 		PROTO :VARARG
 	gtk_source_search_settings_get_regex_enabled 		PROTO :VARARG
 	gtk_source_search_settings_set_regex_enabled 		PROTO :VARARG

