  	gtk_toggle_button_new 	PROTO	:VARARG
  	gtk_toggle_button_new_with_label 	PROTO	:VARARG
  	gtk_toggle_button_new_with_mnemonic 	PROTO	:VARARG
 	gtk_toggle_button_set_mode 	PROTO	:VARARG
 	gtk_toggle_button_get_mode 	PROTO	:VARARG
 	gtk_toggle_button_toggled 	PROTO	:VARARG
 	gtk_toggle_button_get_active 	PROTO	:VARARG
 	gtk_toggle_button_set_active 	PROTO	:VARARG
 	gtk_toggle_button_get_inconsistent 	PROTO	:VARARG
 	gtk_toggle_button_set_inconsistent 	PROTO	:VARARG

