
		gtk_menu_shell_append  PROTO :VARARG 
		gtk_menu_shell_prepend  PROTO :VARARG 
		gtk_menu_shell_insert  PROTO :VARARG 
		gtk_menu_shell_deactivate  PROTO :VARARG 
		gtk_menu_shell_select_item  PROTO :VARARG 
		gtk_menu_shell_select_first  PROTO :VARARG 
		gtk_menu_shell_deselect  PROTO :VARARG 
		gtk_menu_shell_activate_item  PROTO :VARARG 
		gtk_menu_shell_cancel  PROTO :VARARG 
		gtk_menu_shell_set_take_focus  PROTO :VARARG 
		gtk_menu_shell_get_take_focus  PROTO :VARARG 
		gtk_menu_shell_get_selected_item  PROTO :VARARG 
		gtk_menu_shell_get_parent_shell  PROTO :VARARG 
		gtk_menu_shell_bind_model  PROTO :VARARG 
	
